language: cpp
os: 
  - osx
  - linux
compiler:
  - clang
  - gcc

sudo: required
      
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [[ $TRAVIS_OS_NAME==osx ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME==osx && -z `brew list | grep doxygen` ]]; then brew install doxygen; fi
  - if [[ $TRAVIS_OS_NAME==osx && -z `brew list | grep cmake` ]]; then brew install cmake; fi
  - if [[ $TRAVIS_OS_NAME==osx ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ $TRAVIS_OS_NAME==osx && -z `brew list | grep ninja` ]]; then brew install ninja; fi
  - if [[ $TRAVIS_OS_NAME==linux ]]; then sudo apt-get -qq update; fi
  - if [[ $TRAVIS_OS_NAME==linux ]]; then sudo apt-get install -y cmake ninja-build doxygen; fi
  
before_script:
  - cmake --version
  - cmake -G "Ninja" -DBUILD_TEST=TRUE
script:
  - ninja pondertest
  - ninja doc
  - ./test/pondertest

notifications:
  email:
    on_failure: always
    on_success: change
