language: cpp
os: 
  - osx
  - linux
compiler:
  - clang
  - gcc
osx_image: xcode7.3

sudo: required
dist: trusty
      
before_install:
  - echo "Lang: $LANG. OS: $TRAVIS_OS_NAME. CC: $CC."
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -z `brew list | grep doxygen` ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -z `brew list | grep cmake` ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake doxygen; fi
  
before_script:
  - cmake --version
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G Xcode -DBUILD_TEST=ON; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. -G "Unix Makefiles" -DBUILD_TEST=ON; fi
script:
  - cmake --build . --target pondertest --config Release && ./test/Release/pondertest 

notifications:
  email:
    on_failure: always
    on_success: change


