language: cpp
os: 
  - osx
  - linux
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - ninja-build
      
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep doxygen` == '' ]]; then brew install doxygen; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep cmake` == '' ]]; then brew install cmake; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ $TRAVIS_OS_NAME == osx && `brew list | grep ninja` == '' ]]; then brew install ninja; fi
before_script:
  - cmake --version
  - cmake -G "Ninja" -DBUILD_TEST=TRUE
script:
  - ninja pondertest
  - ninja doc
  - ./test/pondertest

notifications:
  email:
    on_failure: always
