language: cpp
os: 
  - osx
  - linux
compiler:
  - clang
  - gcc

sudo: required
dist: trusty
      
before_install:
  - echo "Lang:$LANG OS:$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -z `brew list | grep doxygen` ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && -z `brew list | grep cmake` ]]; then brew install cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake doxygen; fi
  
before_script:
  - cmake --version
  - cmake -G "Unix Makefiles" -DBUILD_TEST=TRUE
script:
  - make pondertest
  - make doc
  - ./test/pondertest

notifications:
  email:
    on_failure: always
    on_success: change


