# Site settings

title: Ponder
description: >
  Ponder is a C++11 reflection library. This is useful for data-driven applications,
  script binding, automatic editing, etc.
baseurl: /ponder

markdown: kramdown
highlighter: pygments

paginate: 10

sass:
  sass_dir: css
  style: compressed
    
ponder:
  dev: 0
  rss: /feed.xml

github:
  url: https://github.com/billyquith/ponder
  user: billyquith
  
stackoverflow:
  url: http://stackoverflow.com/questions/tagged/ponder
