# Site settings
title: Ponder
#email: your-email@domain.com
description: >
  Ponder is a C++11 reflection library. This is useful for data-driven applications,
  script binding, automatic editing, etc.
url: "http://billyquith.github.io/ponder/"
#twitter_username: jekyllrb
github_username:  billyquith

markdown: redcarpet
pygments: true
